[package]
name = "kangklip_credits"
version = "0.1.0"
description = "KangKlip credits program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "kangklip_credits"

[features]
no-entrypoint = []

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"

